### PR TITLE
FB: Double tap to sleep anywhere on the lock screen (1/2)

### PR DESCRIPTION
**Pull request by DJLaMontagneIII**

### CODE REVIEW

**Comment by DJLaMontagneIII** [comment]
Hey guys noticed a user was asking for this in the OPO XDA thread.

**Comment by fusionjack** [comment]
thanks for these commits, trying them right now...

**Comment by fusionjack** [comment]
@DJLaMontagneIII, somehow it can't be disabled. i disabled this option in security settings, but the feature is still working. could you check this?
the value is applied correctly, i checked it with "settings get system double_tap_sleep_anywhere"

**Comment by DJLaMontagneIII** [comment]
Yea that's weird its enabling/ disabling for me, running a sync from last night on bacon. Made a little screen record of it in action.. https://drive.google.com/file/d/0B-WKHhTljLSYZEFMdFVqdTR2cWs/view?usp=docslist_api

**Comment by DJLaMontagneIII** [comment]
@fusionjack, Seems if double tap status bar  to sleep is enabled it won't allow disabling double tap on lockscreen

**Comment by fusionjack** [comment]
a good catch. i think i know what happens, the first commit from Evisceration makes double tap on lockscreen always on. i'll try to remove it.

**Comment by fusionjack** [comment]
now it is working as intended.
i'll cherry-pick only one commit from your github and close this pull request.
many thanks @DJLaMontagneIII !

**Pull request closed without merging**
